import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: "Isaac",
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true
        },
        {
            name: "Bwire",
            email: 'user@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: false,
        },
    ],
    products: [
        {
            // _id : '1',
            name: 'iphone 13',
            slug: 'iphone 13',
            category: 'phone',
            image: '/images/image.png',
            price: 120,
            priceTsh: 200000,
            countInStock: 10,
            brand: 'Apple',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product'
        },
        {
            // _id : '2',
            name: 'nike sneakers',
            slug: 'nike sneakers',
            category: 'shoes',
            image: '/images/nike.png',
            price: 60,
            priceTsh: 200000,
            countInStock: 0,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 11,
            description: 'high quality shoes'
        },
        {
            // _id : '3',
            name: 'mens shirts',
            slug: 'mens slim shirt',
            category: 'clothes',
            image: '/images/shirt.png',
            price: 12,
            priceTsh: 200000,
            countInStock: 16,
            brand: 'polo',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality mens clothes'
        },
        {
            // _id : '4',
            name: 'dress shirt',
            slug: 'dress shirt',
            category: 'clothes',
            image: '/images/shirt2.png',
            price: 6,
            priceTsh: 200000,
            countInStock: 16,
            brand: 'cotton shirt',
            rating: 4.5,
            numReviews: 11,
            description: 'high quality product'
        },
        {
            // _id : '5',
            name: 'sunglasses',
            slug: 'sunglasses',
            category: 'eye wear',
            image: '/images/sunglasses.png',
            price: 10,
            priceTsh: 200000,
            countInStock: 16,
            brand: 'rayband',
            rating: 5.0,
            numReviews: 15,
            description: 'high end sunglasses'
        },
        {
            // _id : '6',
            name: 'potatoes',
            slug: 'potatoes',
            category: 'farm produce',
            image: '/images/potatoes.png',
            price: 100,
            priceTsh: 200000,
            countInStock: 16,
            brand: 'farm',
            rating: 4.8,
            numReviews: 10,
            description: 'high quality produce from Tanzania'
        },
        {
            // _id : '7',
            name: 'apple mouse',
            slug: 'apple mouse',
            category: 'mouse',
            image: '/images/appleMouse.png',
            price: 20,
            priceTsh: 200000,
            countInStock: 200,
            brand: 'Apple',
            rating: 5,
            numReviews: 20,
            description: 'high quality product'
        },
        {
            // _id : '8',
            name: 'Viviscal',
            slug: 'Viviscal',
            category: 'beauty',
            image: '/images/Viviscal.png',
            price: 30,
            priceTsh: 200000,
            countInStock: 30,
            brand: 'Viviscal',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shampoo'
        },
        {
            // _id : '9',
            name: 'mascara',
            slug: 'women mascara',
            category: 'beauty',
            image: '/images/mascara.png',
            price: 50,
            priceTsh: 200000,
            countInStock: 100,
            brand: 'thrive',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality mascara for women'
        },
        {
            // _id : '10',
            name: 'comforter',
            slug: 'comforter sets',
            category: 'bedding',
            image: '/images/comforter.png',
            price: 75,
            priceTsh: 200000,
            countInStock: 30,
            brand: 'Madison Park',
            rating: 4,
            numReviews: 9,
            description: 'high quality comforter sets'
        },
        {
            // _id : '11',
            name: 'dining set',
            slug: 'indoor dining set',
            category: 'furniture',
            image: '/images/diningSet.png',
            price: 1000,
            priceTsh: 200000,
            countInStock: 14,
            brand: 'Rustic Furniture Depot',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality furniture'
        },
        {
            // _id : '12',
            name: 'macbook',
            slug: 'macbook laptop',
            category: 'computer',
            image: '/images/macbook.png',
            price: 1300,
            priceTsh: 1500000,
            countInStock: 20,
            brand: 'Apple',
            rating: 5,
            numReviews: 15,
            description: 'High performing computer with 1M chip technology'
        }
    ]
}
export default data;